# Generated by Django 4.2.7 on 2026-03-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Unique employee identifier, e.g. EMP-001', max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(help_text='Work email address', max_length=254, unique=True)),
                ('department', models.CharField(choices=[('Engineering', 'Engineering'), ('Product', 'Product'), ('Design', 'Design'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('HR', 'Human Resources'), ('Finance', 'Finance'), ('Operations', 'Operations'), ('Legal', 'Legal'), ('Customer Support', 'Customer Support'), ('Other', 'Other')], default='Other', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['department'], name='employees_e_departm_e28f46_idx'), models.Index(fields=['employee_id'], name='employees_e_employe_514cc5_idx')],
            },
        ),
    ]
